-- Syte SEO Suite — Technical SEO + AEO persistence patch.
-- Run AFTER supabase-schema.sql and supabase-schema-reports.sql.
-- Safe to re-run: everything uses IF NOT EXISTS.

-- 1. Technical SEO tasks — generated by AI triage of WebCEO/GSC audit data.
create table if not exists syte_suite_tseo_tasks (
  id uuid primary key default gen_random_uuid(),
  client_id uuid references syte_suite_clients(id) on delete cascade,
  client_name text,
  title text not null,
  description text,
  priority text default 'medium',     -- critical | high | medium | low
  page_url text,
  fix_type text,                       -- meta_title | meta_description | canonical | schema | etc.
  copy_paste_fix text,
  impact text,                         -- high | medium | low
  effort text,                         -- quick | moderate | complex
  status text default 'open',          -- open | done | verified | failed
  assignee text,
  data_source text,                    -- WebCEO | GSC
  created_at timestamptz default now()
);

create index if not exists syte_suite_tseo_tasks_client_idx
  on syte_suite_tseo_tasks(client_id, created_at desc);

alter table syte_suite_tseo_tasks disable row level security;

-- 2. AEO optimization results — generated optimizations per page per client.
create table if not exists syte_suite_aeo_results (
  id uuid primary key default gen_random_uuid(),
  client_id uuid references syte_suite_clients(id) on delete cascade,
  url text not null,
  path text,
  sessions int default 0,
  priority text,
  optimizations jsonb,                 -- array of {type, name, description, implementation, where}
  error text,
  generated_at timestamptz default now(),
  created_at timestamptz default now()
);

create index if not exists syte_suite_aeo_results_client_idx
  on syte_suite_aeo_results(client_id, generated_at desc);

alter table syte_suite_aeo_results disable row level security;

-- 3. Add columns to clients (safe to re-run).
alter table syte_suite_clients add column if not exists looker_url text;
alter table syte_suite_clients add column if not exists client_type text;  -- 'ecommerce' | 'lead_gen'
-- The Google account email that has access to this client's GA4 + GSC
-- properties. Captured when the operator picks properties via the Google
-- Connections picker. Used as login_hint on subsequent visits so the right
-- account is selected automatically (and to warn if the wrong one is in use).
alter table syte_suite_clients add column if not exists google_account_email text;
-- Per-API bindings — for the (common) case where a single client has GA4
-- under one Google account and Search Console under a different one (e.g.
-- the brand owns GSC but the agency hosts GA4). When set, these win over
-- google_account_email for their respective API; when unset they fall
-- back to it. Captured automatically when the operator picks a property
-- in the picker — whichever account was active gets bound to that API.
alter table syte_suite_clients add column if not exists ga4_account_email text;
alter table syte_suite_clients add column if not exists gsc_account_email text;

-- 4. AEO Deep Optimizations — full-page rewrites with FAQ + changes log.
-- Distinct from syte_suite_aeo_results (which holds the 5-snippet quick-wins).
create table if not exists syte_suite_aeo_deep (
  id uuid primary key default gen_random_uuid(),
  client_id uuid references syte_suite_clients(id) on delete cascade,
  client_name text,
  page_url text not null,
  page_title text,
  description text,                    -- HTML
  faq text,                            -- HTML
  changes_description jsonb,           -- [{title, detail}, ...]
  changes_faq jsonb,                   -- [{title, detail}, ...]
  product_schema text,                 -- JSON-LD <script>
  faq_schema text,                     -- JSON-LD <script>
  internal_links jsonb,                -- [{anchor, targetHint, reason}, ...]
  generated_at timestamptz default now(),
  created_at timestamptz default now()
);

-- Re-run safe: add internal_links column if missing on existing installs.
alter table syte_suite_aeo_deep add column if not exists internal_links jsonb;

create index if not exists syte_suite_aeo_deep_client_idx
  on syte_suite_aeo_deep(client_id, generated_at desc);

alter table syte_suite_aeo_deep disable row level security;

-- 5. Content Engine — Quick Blog generations (topic-driven, persisted).
-- Separate from syte_suite_cms_queue (pre-push) and content history in
-- localStorage. This table is the single source of truth for blogs
-- generated via the Quick Blog Generator.
create table if not exists syte_suite_content_blogs (
  id uuid primary key default gen_random_uuid(),
  client_id uuid references syte_suite_clients(id) on delete cascade,
  client_name text,
  topic text not null,
  keyword text,
  length int default 1500,
  output text,                         -- full raw model output (body + metas + schemas + QA)
  tab text default 'New Article',      -- 'Auto Write' | 'New Article' | 'Quick Blog' | etc.
  opportunity_type text,               -- from Topic Research (low-hanging-fruit, content-gap, etc.)
  generated_at timestamptz default now(),
  created_at timestamptz default now()
);

-- Safe to re-run: add columns if missing on existing installs.
alter table syte_suite_content_blogs add column if not exists tab text default 'New Article';
alter table syte_suite_content_blogs add column if not exists opportunity_type text;

create index if not exists syte_suite_content_blogs_client_idx
  on syte_suite_content_blogs(client_id, generated_at desc);

alter table syte_suite_content_blogs disable row level security;

-- 6. Cached report data — GA4 + GSC metrics per client per month.
-- Avoids re-fetching every time the report page is opened.
create table if not exists syte_suite_report_cache (
  id uuid primary key default gen_random_uuid(),
  client_id uuid references syte_suite_clients(id) on delete cascade,
  month text not null,                   -- YYYY-MM
  data jsonb not null,                   -- full reportData object
  fetched_at timestamptz default now()
);

create unique index if not exists syte_suite_report_cache_uniq
  on syte_suite_report_cache(client_id, month);

alter table syte_suite_report_cache disable row level security;

-- 7. Generated report content — the actual artefacts produced by a
-- generation run (Alice email, microsite JSON, QA, AEO probe, frozen
-- reportData snapshot). Persisted so reopening the tool can re-render
-- the report without re-running Claude / re-querying GA4+GSC.
-- One row per client per month; updated on regeneration.
--
-- The base table normally lives in supabase-schema-reports.sql, but we
-- recreate it here with `if not exists` so this file works as a single
-- self-contained patch even if reports.sql hasn't been run.
create table if not exists syte_suite_report_generated_log (
  id uuid primary key default gen_random_uuid(),
  client_id uuid references syte_suite_clients(id) on delete cascade,
  month text not null,
  generated_at timestamptz default now(),
  qa_score int,
  email_subject text,
  report_type text,                     -- 'full' | 'aeo'
  created_at timestamptz default now(),
  unique (client_id, month)
);

create index if not exists syte_suite_report_generated_log_client_month_idx
  on syte_suite_report_generated_log(client_id, month desc);

alter table syte_suite_report_generated_log disable row level security;

alter table syte_suite_report_generated_log add column if not exists email_body text;
alter table syte_suite_report_generated_log add column if not exists microsite_json jsonb;
alter table syte_suite_report_generated_log add column if not exists qa jsonb;
alter table syte_suite_report_generated_log add column if not exists aeo_probe jsonb;
alter table syte_suite_report_generated_log add column if not exists report_data jsonb;
-- Operator-edited microsite HTML. When set, the report viewer renders this
-- verbatim instead of re-building from microsite_json + report_data — so
-- in-place visual edits made before sending survive the round-trip.
alter table syte_suite_report_generated_log add column if not exists microsite_html_override text;

-- 8. Rejected optimizations — operator-driven blocklist so a task or AEO
-- snippet that's been explicitly rejected doesn't reappear next month
-- when the audit / sitemap re-discovers the same underlying issue.
--
-- Technical SEO rejections are keyed by a stable dedup key
-- (client_id|page_url|title) so a freshly-triaged task with a new UUID
-- but the same logical issue is filtered out automatically.
create table if not exists syte_suite_tseo_rejections (
  client_id uuid references syte_suite_clients(id) on delete cascade,
  dedup_key text not null,
  reason text,
  rejected_at timestamptz default now(),
  primary key (client_id, dedup_key)
);

create index if not exists syte_suite_tseo_rejections_client_idx
  on syte_suite_tseo_rejections(client_id);

alter table syte_suite_tseo_rejections disable row level security;

-- AEO rejections are keyed per (client, page_url, opt_key) where opt_key
-- combines the optimization's type + name. A re-run that produces an
-- optimization with the same type+name on the same page is filtered out.
create table if not exists syte_suite_aeo_rejections (
  client_id uuid references syte_suite_clients(id) on delete cascade,
  page_url text not null,
  opt_key text not null,
  reason text,
  rejected_at timestamptz default now(),
  primary key (client_id, page_url, opt_key)
);

create index if not exists syte_suite_aeo_rejections_client_idx
  on syte_suite_aeo_rejections(client_id);

alter table syte_suite_aeo_rejections disable row level security;
