-- Syte SEO Suite — Technical SEO + AEO persistence patch.
-- Run AFTER supabase-schema.sql and supabase-schema-reports.sql.
-- Safe to re-run: everything uses IF NOT EXISTS.

-- 1. Technical SEO tasks — generated by AI triage of WebCEO/GSC audit data.
create table if not exists syte_suite_tseo_tasks (
  id uuid primary key default gen_random_uuid(),
  client_id uuid references syte_suite_clients(id) on delete cascade,
  client_name text,
  title text not null,
  description text,
  priority text default 'medium',     -- critical | high | medium | low
  page_url text,
  fix_type text,                       -- meta_title | meta_description | canonical | schema | etc.
  copy_paste_fix text,
  impact text,                         -- high | medium | low
  effort text,                         -- quick | moderate | complex
  status text default 'open',          -- open | done | verified | failed
  assignee text,
  data_source text,                    -- WebCEO | GSC
  created_at timestamptz default now()
);

create index if not exists syte_suite_tseo_tasks_client_idx
  on syte_suite_tseo_tasks(client_id, created_at desc);

alter table syte_suite_tseo_tasks disable row level security;

-- 2. AEO optimization results — generated optimizations per page per client.
create table if not exists syte_suite_aeo_results (
  id uuid primary key default gen_random_uuid(),
  client_id uuid references syte_suite_clients(id) on delete cascade,
  url text not null,
  path text,
  sessions int default 0,
  priority text,
  optimizations jsonb,                 -- array of {type, name, description, implementation, where}
  error text,
  generated_at timestamptz default now(),
  created_at timestamptz default now()
);

create index if not exists syte_suite_aeo_results_client_idx
  on syte_suite_aeo_results(client_id, generated_at desc);

alter table syte_suite_aeo_results disable row level security;

-- 3. Add looker_url to clients (may already exist from earlier patches).
alter table syte_suite_clients add column if not exists looker_url text;

-- 4. AEO Deep Optimizations — full-page rewrites with FAQ + changes log.
-- Distinct from syte_suite_aeo_results (which holds the 5-snippet quick-wins).
create table if not exists syte_suite_aeo_deep (
  id uuid primary key default gen_random_uuid(),
  client_id uuid references syte_suite_clients(id) on delete cascade,
  client_name text,
  page_url text not null,
  page_title text,
  description text,                    -- HTML
  faq text,                            -- HTML
  changes_description jsonb,           -- [{title, detail}, ...]
  changes_faq jsonb,                   -- [{title, detail}, ...]
  product_schema text,                 -- JSON-LD <script>
  faq_schema text,                     -- JSON-LD <script>
  internal_links jsonb,                -- [{anchor, targetHint, reason}, ...]
  generated_at timestamptz default now(),
  created_at timestamptz default now()
);

-- Re-run safe: add internal_links column if missing on existing installs.
alter table syte_suite_aeo_deep add column if not exists internal_links jsonb;

create index if not exists syte_suite_aeo_deep_client_idx
  on syte_suite_aeo_deep(client_id, generated_at desc);

alter table syte_suite_aeo_deep disable row level security;

-- 5. Content Engine — Quick Blog generations (topic-driven, persisted).
-- Separate from syte_suite_cms_queue (pre-push) and content history in
-- localStorage. This table is the single source of truth for blogs
-- generated via the Quick Blog Generator.
create table if not exists syte_suite_content_blogs (
  id uuid primary key default gen_random_uuid(),
  client_id uuid references syte_suite_clients(id) on delete cascade,
  client_name text,
  topic text not null,
  keyword text,
  length int default 1500,
  output text,                         -- full raw model output (body + metas + schemas + QA)
  generated_at timestamptz default now(),
  created_at timestamptz default now()
);

create index if not exists syte_suite_content_blogs_client_idx
  on syte_suite_content_blogs(client_id, generated_at desc);

alter table syte_suite_content_blogs disable row level security;
